### ISSUE TITLE
Unspecified Error

### ISSUE THREAD

**Issue by joaomatossilva** [frej/fast-export#111]
Hi,

I'm trying to convert a big repository (22k revisions) from hg to git. 
I'm having an issue but the error message is not that helpfull

```
Development: Exporting simple delta revision 10001/11000 with 0/1/0 added/changed/removed files
Development: Exporting simple delta revision 10002/11000 with 0/1/0 added/changed/removed files
athe-#14-paid-membership: Exporting simple delta revision 10003/11000 with 5/14/0 added/changed/removed files
Traceback (most recent call last):
  File "C:/Mindbus/fast-export/hg-fast-export.py", line 529, in <module>
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "C:/Mindbus/fast-export/hg-fast-export.py", line 427, in hg2git
    sob,brmap,hgtags,encoding,fn_encoding)
  File "C:/Mindbus/fast-export/hg-fast-export.py", line 248, in export_commit
    export_file_contents(ctx,man,added,hgtags,fn_encoding)
  File "C:/Mindbus/fast-export/hg-fast-export.py", line 141, in export_file_contents
    wr(d)
  File "C:/Mindbus/fast-export/hg-fast-export.py", line 37, in wr
    wr_no_nl(msg)
  File "C:/Mindbus/fast-export/hg-fast-export.py", line 34, in wr_no_nl
    sys.stdout.write(msg)
IOError: [Errno 22] Invalid argument

```

Where can I get a bit more information where the error is happening to find the cause?

Thanks

**Comment by frej** [comment]
Please see issue #103 for how you can debug this type of crash:

> In .git/fast_import_crash_<pid>, desribed in the "Crash Reports" section of the git fast-import man-page. Be aware that fast-export runs asynchronously to fast-import, so it's not unusual to see (if fast-exports feeds fast-import bad data) trace printouts from fast export for commits up to no. <x+delta>, and then a crash report from fast-export (typically a broken pipe). When you then check the fast-import crash log you see that fast-import already crashed on the earlier commit <x>.

**Comment by frej** [comment]
Any progress? If you managed to solve your problem please close this ticket.
