### ISSUE TITLE
MemoryError when running hg-fast-export.sh on chunky repository

### ISSUE THREAD

**Issue by peterlindgren** [frej/fast-export#146]
I'm trying to convert a repository with about 41000 changesets and a lot of binary data. The repositiory doesn't use the large files extension. After about 2000 revisions fast-export fails:

> master: Exporting simple delta revision 2607/41300 with 7/3/0 added/changed/removed files
Traceback (most recent call last):
  File "E:/work/fast-export/hg-fast-export.py", line 530, in <module>
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "E:/work/fast-export/hg-fast-export.py", line 428, in hg2git
    sob,brmap,hgtags,encoding,fn_encoding)
  File "E:/work/fast-export/hg-fast-export.py", line 250, in export_commit
    export_file_contents(ctx,man,changed,hgtags,fn_encoding)
  File "E:/work/fast-export/hg-fast-export.py", line 134, in export_file_contents
    d=ctx.filectx(file).data()
  File "C:\Python27\lib\site-packages\mercurial\context.py", line 967, in data
    return self._filelog.read(self._filenode)
  File "C:\Python27\lib\site-packages\mercurial\filelog.py", line 130, in read
    return storageutil.filtermetadata(self.revision(node))
  File "C:\Python27\lib\site-packages\mercurial\filelog.py", line 91, in revision
    return self._revlog.revision(node, _df=_df, raw=raw)
  File "C:\Python27\lib\site-packages\mercurial\revlog.py", line 1585, in revision
    bins = self._chunks(chain, df=_df, targetsize=targetsize)
  File "C:\Python27\lib\site-packages\mercurial\revlog.py", line 1480, in _chunks
    ladd(decomp(buffer(data, chunkstart - offset, chunklength)))
  File "C:\Python27\lib\site-packages\mercurial\revlog.py", line 1871, in decompress
    return _zlibdecompress(data)
MemoryError

I'm running on Windows 10 x64 via Git Bash, Python 2.7.11, Mercurial 4.8.1, Git 2.20.0.windows.1. There was no crazy memory usage while running fast-export and at the moment of the error the machine had about 26GB free memory so it's probably something wrong with the source repository.

Any ideas as to what I could do to get more information on the error or work around it?

**Comment by frej** [comment]
As the error is deep inside Mercurial I would add a print out dumping the Mercurial revision on entry to `export_commit` and then try to check out that revision using straight `hg`.

**Comment by frej** [comment]
Any update on this? It would be good to know if this is an issue with fast-export or just a corrupt hg repo in which case I can close this issue.

**Comment by sikmir** [comment]
I had the same error with 32-bit Python, switching to 64-bit Python solved the problem.
