### ISSUE TITLE
error: cannot lock ref 'refs/heads/action': 'refs/heads/action/ban' exists; cannot create 'refs/heads/action'

### ISSUE THREAD

**Issue by gegogi** [frej/fast-export#148]
I am converting a big hg repo to a git repo.
After a long period of conversion( several hours ), I got this error and have no clue.

`
PROG: Exporting simple delta revision 26845/40414 with 0/4/5205 added/changed/removed files
Traceback (most recent call last):
  File "/root/fast-export/hg-fast-export.py", line 650, in <module>
    plugins=plugins_dict))
  File "/root/fast-export/hg-fast-export.py", line 506, in hg2git
    plugins)
  File "/root/fast-export/hg-fast-export.py", line 317, in export_commit
    export_file_contents(ctx,man,changed,hgtags,fn_encoding,plugins)
  File "/root/fast-export/hg-fast-export.py", line 163, in export_file_contents
    gitSha=marks_cache[int(revnum)]
KeyError: 5200
error: cannot lock ref 'refs/heads/action': 'refs/heads/action/ban' exists; cannot create 'refs/heads/action'
git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:     565000
Total objects:       561397 (   4348037 duplicates                  )
      blobs  :       356832 (   3933297 duplicates     276588 deltas of     335384 attempts)
      trees  :       177720 (    414740 duplicates     123521 deltas of     166995 attempts)
      commits:        26845 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:          70 (       925 loads     )
      marks:        1048576 (     26845 unique    )
      atoms:         113685
Memory total:         57195 KiB
       pools:         30711 KiB
     objects:         26484 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =       4096
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 8589934592
pack_report: pack_used_ctr            =    1015162
pack_report: pack_mmap_calls          =     137492
pack_report: pack_open_windows        =          8 /          9
pack_report: pack_mapped              = 8589934592 / 8589934592
---------------------------------------------------------------------
`

**Comment by frej** [comment]
In contrast to Hg where branch names are just strings, Git branch names
behave just as files and directories. In your case 'action' would have
to be both a file and a directory, something that cannot exist.

What you probably want to do is to use a branch mapping file to massage
the branch names.

**Comment by frej** [comment]
No activity in over six months.
