### ISSUE TITLE
fatal: Invalid raw date

### ISSUE THREAD

**Issue by wRAR** [frej/fast-export#15]
hg-fast-export fails on a checkout of ssh://anonhg@hg.illumos.org/illumos-gate

```
master: Exporting simple delta revision 7371/14114 with 0/7/0 added/changed/removed files
fatal: Invalid raw date "<devnull@localhost> 1219151827 -0600" in ident:  <Gerald Jelinek> <devnull@localhost> 1219151827 -0600
fast-import: dumping crash report to .git/fast_import_crash_1875
Traceback (most recent call last):
  File "/usr/share/hg-fast-export/hg-fast-export.py", line 387, in <module>
    options.statusfile,authors=a,sob=options.sob,force=options.force))
  File "/usr/share/hg-fast-export/hg-fast-export.py", line 321, in hg2git
    c=export_commit(ui,repo,rev,old_marks,max,c,authors,sob,brmap)
  File "/usr/share/hg-fast-export/hg-fast-export.py", line 214, in export_commit
    export_file_contents(ctx,man,changed)
  File "/usr/share/hg-fast-export/hg-fast-export.py", line 125, in export_file_contents
    wr(d)
  File "/usr/share/hg-fast-export/hg-fast-export.py", line 26, in wr
    sys.stdout.write(msg)
IOError: [Errno 32] Broken pipe
```

The crash dump contains this command:

```
  commit refs/heads/master
  mark :7371
* committer <Gerald Jelinek> <devnull@localhost> 1219151827 -0600
```

**Comment by kanup** [comment]
brainz solution of using authors.txt file worked for us.

**Comment by trevor** [comment]
I hit this issue too. The -A authors.txt worked with this as content:

```
<>=devnull <devnull@localhost>
```

Could this be made a default?

**Comment by timraasveld** [comment]
Update to @brianz ' excellent advice. In the latest version of hg-fast-export, each key and value of authors.txt should be quoted to avoid the error: `Invalid file format in [authors.txt], line 1`

So it becomes:
```
"<>"="devnull <devnull@localhost>"
"\<\>"="devnull <devnull@localhost>"
