### ISSUE TITLE
Failing on Macos Catalina

### ISSUE THREAD

**Issue by iainfogg** [frej/fast-export#181]
Hi, I expect this is something I'm missing, but I'm not at all used to running stuff with python, I'm afraid. I have a script which calls `hg-fast-export.sh` which had been working fine until I upgraded to Macos Catalina. Since then, I get this error when trying to convert a repo:

```
Traceback (most recent call last):
  File "/Users/iainfogg/Sources/misc/fast-export/hg-fast-export.py", line 7, in <module>
    from mercurial.scmutil import revsymbol
  File "/usr/local/lib/python2.7/site-packages/mercurial/scmutil.py", line 19, in <module>
  File "/usr/local/lib/python2.7/site-packages/mercurial/i18n.py", line 15, in <module>
  File "/usr/local/lib/python2.7/site-packages/mercurial/encoding.py", line 24, in <module>
  File "/usr/local/lib/python2.7/site-packages/mercurial/policy.py", line 107, in importmod
  File "/usr/local/lib/python2.7/site-packages/mercurial/policy.py", line 67, in _importfrom
ImportError: cannot import name parsers
```

I have read that Python 2.7 is being deprecated in Macos Catalina, and will be removed in the following version, which made me think that may be related. However, I still seem to have Python 2.7 installed and working through `homebrew`. Running `which python` gives `/usr/local/bin/python`, which is a symlink to `../Cellar/python@2/2.7.17/bin/python`, and if I run `python --version` I get `Python 2.7.17`. Also, the stack trace above is showing a bunch of Python 2.7 files being used.

So, I'm not clear why this would have stopped working - do you have any idea? I am up to date and on the latest commit of fast-export https://github.com/frej/fast-export/commit/3af916d6641cd0b22c545c1a9f2875e4f275305b

Thanks

**Comment by iainfogg** [comment]
For info, I just ran `pip install mercurial` again, and it's now working. Don't know anything about Python to know why that was needed, but I'm up and running again.

And thanks @frej for a great piece of software, this is a huge help in a bunch of conversions we need to do!
