### ISSUE TITLE
TypeError: 'status' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by GregWoods** [frej/fast-export#196]
I'm not sure where to go from here. Any pointers would be appreciated.

Ubuntu 18.04 (on Windows Subsystem for Linux)
Python2   2.7.16
Python3   3.7.3
Mercurial  5.3

I'm happy to supply any other info.

Greg

Full output:
```
root@VL16:/mnt/c/Projects/assortedutilities# ../fast-export/hg-fast-export.sh -r ../assortedutilities-hg --force -n
master: Exporting full revision 1/150 with 494/0/0 added/changed/removed files
Traceback (most recent call last):
  File "/mnt/c/Projects/fast-export/hg-fast-export.py", line 689, in <module>
    plugins=plugins_dict))
  File "/mnt/c/Projects/fast-export/hg-fast-export.py", line 541, in hg2git
    plugins)
  File "/mnt/c/Projects/fast-export/hg-fast-export.py", line 323, in export_commit
    f=repo.status(parents[0],revnode)[:3]
TypeError: 'status' object has no attribute '__getitem__'
/usr/lib/git-core/git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:          550 (        27 duplicates                  )
      blobs  :          468 (        26 duplicates        278 deltas of        464 attempts)
      trees  :           80 (         1 duplicates          0 deltas of          0 attempts)
      commits:            2 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           1 (         1 loads     )
      marks:           1024 (         2 unique    )
      atoms:            455
Memory total:          2344 KiB
       pools:          2110 KiB
     objects:           234 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =       4096
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 35184372088832
pack_report: pack_used_ctr            =          2
pack_report: pack_mmap_calls          =          1
pack_report: pack_open_windows        =          1 /          1
pack_report: pack_mapped              =    1127899 /    1127899
---------------------------------------------------------------------
```

**Comment by MatthijsBurgh** [comment]
@GregWoods  checkout #197 for the fix

**Comment by stevenaw** [comment]
Thanks for the PR @MatthijsBurgh 
We ran into this issue today as well actually (also Ubuntu 18.04). I'll be giving your branch a try tomorrow too.

**Comment by GregWoods** [comment]
I can confirm the fix worked for me. Thanks everyone!
