### ISSUE TITLE
hg-fast-export fails with TypeError

### ISSUE THREAD

**Issue by mholmes-vls** [frej/fast-export#212]
hg-fast-export fails with TypeError: 'status' object has no attribute '__getitem__'

I'm trying to convert a large repo from Mercurial to Git.  Repo has over 12K commits with hundreds of branches ...

Below is the complete error message.  Using Mercurial 5.3.1, Git 2.17.1 on Ubuntu 18.04 at the 6f9bc6517a738c618f57e2b5ca0ffc03fa482584 commit  in the fast-convert repo.

Please help and thanks in advance!

===============================

Initialized empty Git repository in /home/build/Documents/git-repos/otter/.git/
Loaded 38 authors
master: Exporting full revision 1/6184 with 116/0/0 added/changed/removed files
Traceback (most recent call last):
  File "/home/build/Documents/git-repos/fast-export/hg-fast-export.py", line 665, in <module>
    plugins=plugins_dict))
  File "/home/build/Documents/git-repos/fast-export/hg-fast-export.py", line 517, in hg2git
    plugins)
  File "/home/build/Documents/git-repos/fast-export/hg-fast-export.py", line 305, in export_commit
    f=repo.status(parents[0],revnode)[:3]
TypeError: 'status' object has no attribute '__getitem__'

**Comment by mholmes-vls** [comment]
My apologies!  I updated to the tip of the fast-export repo and re-ran.  Now the conversion seems to work fine.
