### ISSUE TITLE
Trying to convert repo prompts weird KeyError

### ISSUE THREAD

**Issue by JustDevZero** [frej/fast-export#235]
Trying to convert an error prompts an error:

Command executed with:

hg-fast-export.sh -r /home/zero/Projects/migration/project -A ~/Projects/migration/authors --subrepo-map=/home/zero/Projects/migration/mapping.txt --hg-hash --hgtags

master: Exporting simple delta revision 1935/21890 with 2/492/174 added/changed/removed files
Traceback (most recent call last):
  File "/home/zero/Projects/fast-export/hg-fast-export.py", line 719, in <module>
    plugins=plugins_dict))
  File "/home/zero/Projects/fast-export/hg-fast-export.py", line 571, in hg2git
    plugins)
  File "/home/zero/Projects/fast-export/hg-fast-export.py", line 366, in export_commit
    export_file_contents(ctx,man,added,hgtags,fn_encoding,plugins)
  File "/home/zero/Projects/fast-export/hg-fast-export.py", line 210, in export_file_contents
    refresh_gitmodules(ctx)
  File "/home/zero/Projects/fast-export/hg-fast-export.py", line 196, in refresh_gitmodules
    gitmodules+=refresh_hg_submodule(name,subrepo_info)
  File "/home/zero/Projects/fast-export/hg-fast-export.py", line 172, in refresh_hg_submodule
    gitSha=marks_cache[int(revnum)]
KeyError: 10

I understand, that in mapping.txt should be the local relative or absolute path to the subrepo it self, which was converted without errors.

Same error if I remove hg-hash and hgtags.

**Comment by JustDevZero** [comment]
Here is the crash report:

```

fast-import crash report:
    fast-import process: 587364
    parent process     : 587363
    at 2020-06-29 13:38:41 +0000

fatal: Unsupported command: {}

Most Recent Commands Before Crash
---------------------------------
  D utils/static/js/backoffice/calendar.js
  D utils/static/js/backoffice/common.js
  D utils/static/js/backoffice/components.js
  D utils/static/js/backoffice/modal.js
  D utils/static/js/backoffice/mootools-more.js
  D utils/static/js/backoffice/mootools.js
  D utils/static/js/backoffice/wick.js
  D utils/static/js/common.js
  D utils/static/js/swfobject/expressInstall.swf
  D utils/static/js/swfobject/index.html
  D utils/static/js/swfobject/index_dynamic.html
  D utils/static/js/swfobject/src/expressInstall.as
  D utils/static/js/swfobject/src/expressInstall.fla
  D utils/static/js/swfobject/src/swfobject.js
  D utils/static/js/swfobject/swfobject.js
  D utils/static/js/swfobject/test.swf
  D utils/static/mediaplayer/player.swf
  D utils/static/mediaplayer/preview.jpg
  D utils/static/mediaplayer/readme.html
  D utils/static/mediaplayer/swfobject.js
  D utils/static/mediaplayer/video.flv
  D utils/static/mediaplayer/yt.swf
  D utils/static/popeye/js/booking.js
  D utils/static/punymce/blank.htm
  D utils/static/punymce/css/content.css
  D utils/static/punymce/css/editor.css
  D utils/static/punymce/i18n/sv.js
  D utils/static/punymce/img/icons.gif
  D utils/static/punymce/img/icons_uncompressed.png
  D utils/static/punymce/plugins/bbcode.js
  D utils/static/punymce/plugins/bbcode_src.js
  D utils/static/punymce/plugins/editsource/css/editor.css
  D utils/static/punymce/plugins/editsource/editsource.js
  D utils/static/punymce/plugins/editsource/editsource_src.js
  D utils/static/punymce/plugins/editsource/img/icons.gif
  D utils/static/punymce/plugins/emoticons/css/content.css
  D utils/static/punymce/plugins/emoticons/css/editor.css
  D utils/static/punymce/plugins/emoticons/emoticons.js
  D utils/static/punymce/plugins/emoticons/emoticons_src.js
  D utils/static/punymce/plugins/emoticons/img/emoticons.gif
  D utils/static/punymce/plugins/emoticons/img/trans.gif
  D utils/static/punymce/plugins/entities.js
  D utils/static/punymce/plugins/entities_src.js
  D utils/static/punymce/plugins/forceblocks.js
  D utils/static/punymce/plugins/forceblocks_src.js
  D utils/static/punymce/plugins/image/css/editor.css
  D utils/static/punymce/plugins/image/image.js
  D utils/static/punymce/plugins/image/image_src.js
  D utils/static/punymce/plugins/image/img/icons.gif
  D utils/static/punymce/plugins/link/css/editor.css
  D utils/static/punymce/plugins/link/img/icons.gif
  D utils/static/punymce/plugins/link/link.js
  D utils/static/punymce/plugins/link/link_src.js
  D utils/static/punymce/plugins/paste.js
  D utils/static/punymce/plugins/paste_src.js
  D utils/static/punymce/plugins/protect.js
  D utils/static/punymce/plugins/protect_src.js
  D utils/static/punymce/plugins/safari2x.js
  D utils/static/punymce/plugins/safari2x_src.js
  D utils/static/punymce/plugins/tabfocus.js
  D utils/static/punymce/plugins/tabfocus_src.js
  D utils/static/punymce/plugins/textcolor/css/editor.css
  D utils/static/punymce/plugins/textcolor/img/icons.gif
  D utils/static/punymce/plugins/textcolor/textcolor.js
  D utils/static/punymce/plugins/textcolor/textcolor_src.js
  D utils/static/punymce/plugins/textile.js
  D utils/static/punymce/plugins/textile_src.js
  D utils/static/punymce/puny_mce.js
  D utils/static/punymce/puny_mce_cp.js
  D utils/static/punymce/puny_mce_full.js
  D utils/static/punymce/puny_mce_src.js
  D utils/static/slimfancybox/README.txt
  D utils/static/slimfancybox/css/closelabel.gif
  D utils/static/slimfancybox/css/fancy_closebox.png
  D utils/static/slimfancybox/css/loading.gif
  D utils/static/slimfancybox/css/nextlabel.gif
  D utils/static/slimfancybox/css/prevlabel.gif
  D utils/static/slimfancybox/css/slimfancybox.css
  D utils/static/slimfancybox/example.html
  D utils/static/slimfancybox/example.jpg
  D utils/static/slimfancybox/extra/autoactivation.js
  D utils/static/slimfancybox/extra/flickr.js
  D utils/static/slimfancybox/extra/picasaweb.js
  D utils/static/slimfancybox/js/mootools.js
  D utils/static/slimfancybox/js/slimfancybox.js
  D utils/static/slimfancybox/src/autoload.js
  D utils/static/slimfancybox/src/slimfancybox.js
  D utils/templates/helpers/img_gallery.mako
  D utils/templates/popeye/boat_equipments.mako
  D utils/templates/popeye/booking_details.mako
  D utils/templates/popeye/booking_extras.mako
  D utils/templates/popeye/booking_form.mako
  D utils/templates/popeye/booking_prices.mako
  D utils/templates/popeye/ship_details.mako
  D utils/web/__init__.py
  D utils/web/helpers.py
  D utils/web/ui.py
  D utils/web/validator.py
  D .gitmodules
* {}

Active Branch LRU
-----------------
    active_branches = 1 cur, 5 max

  pos  clock name
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   1)   1935 refs/heads/master

Inactive Branches
-----------------
refs/heads/master:
  status      : active loaded
  tip commit  : 624daa7b46e896ae4c87518805afe3996444d493
  old tree    : 05cf2d57db6e74bfeae0579b9d8d01e617f6c736
  cur tree    : 05cf2d57db6e74bfeae0579b9d8d01e617f6c736
  commit clock: 1935
  last pack   : 0


Marks
-----
  exported to .git/hg2git-marks.tmp

-------------------
END OF CRASH REPORT

```

**Comment by JustDevZero** [comment]
Looks like is related to another error i've got on the past:

If I try to map authors on surepo, it fucks up.

Well, no problem, can be skipped.

**Comment by frej** [comment]
[This is a canned reply to issues that contain too little information for effective troubleshooting]

Please have a look at this [blog post](https://www.viget.com/articles/tips-for-writing-better-bug-reports) about writing effective bug reports. For fast-export you should at least:

- Check that your issue is not already covered by an existing issue. If your issue is similar, but not identical to an existing issue, provide a reference.

- Report the version of the fast-export you are running, tag and/or hash.

- Check if your problem is solved by using the latest [released hg-fast-export](https://github.com/frej/fast-export/releases).

- Check that your installed versions of Python and Mercurial meet the minimum requirements as specified in the [README](https://github.com/frej/fast-export/blob/master/README.md).

- Explain what you are trying to do, how you are doing it and in what environment. This includes relevant parts of the used mapping files.

- If your source repository is publicly available, give the URL.

- If hg-fast-export gives an error message and a backtrace, include that in the issue. Also include the relevant parts of the crash report created by `git fast-import`.

**Comment by JustDevZero** [comment]
Unluckly the code is not public to provide a link.

it appears the problem was caused by subrepo rewriting, so instad of rewriting at the time of conversion, I opted for rewrite the history once it's already on git.
