### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by def-gthill** [frej/fast-export#252]
I'm getting this error when I try to use fast-export. I've tried it on a couple different repositories. The full stack trace is:

```
Traceback (most recent call last):
  File "C:/LocalProjects/fast-export/hg-fast-export.py", line 730, in <module>
    plugins=plugins_dict))
  File "C:/LocalProjects/fast-export/hg-fast-export.py", line 542, in hg2git
    if not verify_heads(ui,repo,heads_cache,force,ignore_unnamed_heads,branchesmap):
  File "C:/LocalProjects/fast-export/hg-fast-export.py", line 494, in verify_heads
    sha1=get_git_sha1(sanitized_name)
  File "C:\LocalProjects\fast-export\hg2git.py", line 136, in get_git_sha1
    "--quiet", ref.encode('utf8')])
  File "C:\Python37\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "C:\Python37\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
```

I'm on Windows 10 with Git Bash, Python 3.7.7 64-bit with mercurial 5.6.

**Comment by frej** [comment]
Sorry I can't reproduce this error on Linux with Python 3.7.9 and Mercurial 5.6. Are any of the failing repos publicly available?

@chrisjbillington any Python 3 insights?

**Comment by def-gthill** [comment]
No worries. I got it to work on Python 3.8.6 on Windows 10. Looks like it might be specific to certain versions of Python, and only on Windows. (A quick google turns up similar problems on Windows with other applications.)

**Comment by frej** [comment]
All right, I'll blame this on some Windows brokenness.
