### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CalledProcessError

### ISSUE THREAD

**Issue by kevinsearle** [frej/fast-export#68]
```
[ksearle@dev:~/src/scs] ~/src/fast-export/hg-fast-export.sh -r /home/ksearle/scs
Traceback (most recent call last):
  File "/home/ksearle/src/fast-export/hg-fast-export.py", line 504, in ?
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "/home/ksearle/src/fast-export/hg-fast-export.py", line 382, in hg2git
    if not verify_heads(ui,repo,heads_cache,force,branchesmap):
  File "/home/ksearle/src/fast-export/hg-fast-export.py", line 341, in verify_heads
    sha1=get_git_sha1(sanitized_name)
  File "/home/ksearle/src/fast-export/hg2git.py", line 114, in get_git_sha1
    except subprocess.CalledProcessError:
AttributeError: 'module' object has no attribute 'CalledProcessError'
git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:            0 (         0 duplicates                  )
      blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
      trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
      commits:            0 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           0 (         0 loads     )
      marks:           1024 (         0 unique    )
      atoms:              0
Memory total:          2282 KiB
       pools:          2048 KiB
     objects:           234 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =       4096
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 8589934592
pack_report: pack_used_ctr            =          0
pack_report: pack_mmap_calls          =          0
pack_report: pack_open_windows        =          0 /          0
pack_report: pack_mapped              =          0 /          0
---------------------------------------------------------------------
```

```
[ksearle@dev:~/src/scs] cat /etc/redhat-release
CentOS release 5.8 (Final)
```

```
[ksearle@dev:~/src/scs] hg --version
Mercurial Distributed SCM (version 2.2.2)
```

```
[ksearle@dev:~/src/scs] git --version
git version 1.8.2.1
```

```
[ksearle@dev:~/src/scs] python -V
Python 2.4.3
```

**Comment by frej** [comment]
> [ksearle@dev:~/src/scs] python -V
> Python 2.4.3

Your python is antique, according to
https://www.mercurial-scm.org/wiki/SupportedPythonVersions you need at
least python 2.6 to run a current version of Mercurial. It does not make
sense for fast-export to be more backwards-compatible than Mercurial.

**Comment by kevinsearle** [comment]
Thanks, that's satisfactory. We _are_ in need of upgrading the dev server.
