### ISSUE TITLE
fatal: Missing space after > in ident string

### ISSUE THREAD

**Issue by paulhickman-a365** [frej/fast-export#70]
I am getting an error importing a repository

```
fatal: Missing space after > in ident string:  <unspecified>P <devnull@localhost> 1404822619 +0100
fast-import: dumping crash report to .git/fast_import_crash_5724
Traceback (most recent call last):
  File "../fast-export/hg-fast-export.py", line 504, in <module>
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "../fast-export/hg-fast-export.py", line 404, in hg2git
    sob,brmap,hgtags,encoding,fn_encoding)
  File "../fast-export/hg-fast-export.py", line 244, in export_commit
    export_file_contents(ctx,man,changed,hgtags,fn_encoding)
  File "../fast-export/hg-fast-export.py", line 141, in export_file_contents
    wr(d)
  File "../fast-export/hg-fast-export.py", line 37, in wr
    wr_no_nl(msg)
  File "../fast-export/hg-fast-export.py", line 34, in wr_no_nl
    sys.stdout.write(msg)
IOError: [Errno 32] Broken pipe
```

I think this might be because the committer name is `<unspecified>P` which has a 2nd set of <> causing the parser to configure the user name with the host name. The relevant part of the crash report is:

```
committer Paul Hickman <devnull@localhost> 1404740209 +0100
  data 80
  from :3015
  M 100644 inline Scripts/Migrate-107000001-Client-Paul.sql
  data 797
  
  commit refs/heads/master
  mark :3017
* committer <unspecified>P <devnull@localhost> 1404822619 +0100

Active Branch LRU
-----------------
    active_branches = 1 cur, 5 max

  pos  clock name
   1)   3016 refs/heads/master

Inactive Branches
-----------------
refs/heads/master:
  status      : active loaded
  tip commit  : 3854800d894b00d6f468e99e6cb5eca640a7cf31
  old tree    : 2c9298f523dbb78a984546965e79261220de00da
  cur tree    : 2c9298f523dbb78a984546965e79261220de00da
  commit clock: 3016
  last pack   : 0


Marks
-----
  exported to /home/lfs/dest/.git/hg2git-marks.tmp

-------------------
END OF CRASH REPORT
```

**Comment by frej** [comment]
This is not a fast-export bug, see issues #43 for the complete story. Use the -A option to work around broken Hg repos.

**Comment by stchar** [comment]
@paulhickman-a365, did you managed to fix the issue?

I'm trying to use `-A` flag as described, but have no luck
```
"<unspecified>user <devnull@localhost>"="user <user@example.com>"
```

**Comment by stchar** [comment]
UPD: mapping bellow did the job. Which was not clean according to `README.md`.
```
"<unspecified>user"="user <user@example.com>"
```
