### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by dmgig** [frej/fast-export#83]
I'm trying to convert a mercurial repo to git, but I keep getting the same "string index out of range" failure.

I thought it might have been the slashes in the branch names, so I removed those. I also cloned the repo to get rid of any dead branches.

Can you provide any insight to why this might be occurring? Thank you

```bash
website dgiglio$ ~/Repos/fast-export/hg-fast-export.sh -r ../ll_website
Traceback (most recent call last):
  File "/Users/dgiglio/Repos/fast-export/hg-fast-export.py", line 504, in <module>
    notes=options.notes,encoding=encoding,fn_encoding=fn_encoding))
  File "/Users/dgiglio/Repos/fast-export/hg-fast-export.py", line 382, in hg2git
    if not verify_heads(ui,repo,heads_cache,force,branchesmap):
  File "/Users/dgiglio/Repos/fast-export/hg-fast-export.py", line 340, in verify_heads
    sanitized_name=sanitize_name(b,"branch",branchesmap)
  File "/Users/dgiglio/Repos/fast-export/hg-fast-export.py", line 168, in sanitize_name
    n='/'.join(map(dot,n.split('/')))
  File "/Users/dgiglio/Repos/fast-export/hg-fast-export.py", line 161, in dot
    if name[0] == '.': return '_'+name[1:]
IndexError: string index out of range
git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:            0 (         0 duplicates                  )
      blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
      trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
      commits:            0 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           0 (         0 loads     )
      marks:           1024 (         0 unique    )
      atoms:              0
Memory total:          2282 KiB
       pools:          2048 KiB
     objects:           234 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =       4096
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 8589934592
pack_report: pack_used_ctr            =          0
pack_report: pack_mmap_calls          =          0
pack_report: pack_open_windows        =          0 /          0
pack_report: pack_mapped              =          0 /          0
---------------------------------------------------------------------
```

**Comment by dmgig** [comment]
Looks like I had a branch named `/hotfix/unit_testing` and that was killing it. I'll close this.
